### PR TITLE
Fix `docker-app save` on single-file application

### LINKED ISSUE #351: docker-app save fails with "cannot create file" error in version 0.4.0
**Description**

docker-app save fails with "cannot create file" error in version 0.4.0. 

**Steps to reproduce the issue:**
1. Clone https://github.com/jhrabi/docker-app-save-demo
2. Run docker-app render helloworld.dockerapp from inside the project

**Describe the results you received:**

`Error: cannot create file helloworld.dockerapp/__Dockerfile-docker-app__: open helloworld.dockerapp/__Dockerfile-docker-app__: not a directory`

**Describe the results you expected:**

`Saved application as image: jhrabi/helloworld.dockerapp:0.1.0`

**Additional information you deem important (e.g. issue happens only occasionally):**

If I run the command:

`mkdir -p "open helloworld.dockerapp/__Dockerfile-docker-app__"` 

prior to running the command, the docker-app save works as expected

This functionality also works when I revert back to 0.3.0

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:20:16 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:58 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker-app version`:**

```
Version:      v0.4.0
Git commit:   525d93bc
Built:        Tue Aug 21 13:02:46 2018
OS/Arch:      linux/amd64
Experimental: off
Renderers:    none
```

**Output of `docker info`:**

```
Containers: 77
 Running: 11
 Paused: 0
 Stopped: 66
Images: 1996
Server Version: 18.03.1-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.26GiB
Name: testserver
ID: 4UV7:LJWO:PRJP:PJWY:YEYA:5RLZ:23XJ:TDFB:3G4L:SST7:5RSJ:UBQU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: jhrabi
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on AWS

### PR DESCRIPTION
**Pull request by vdemeester**
Fixes #351 

- [x] needs a regression test though :wink: 
- [x] once merged, we need to do a `0.4.1` release :angel: 

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

File: internal/packager/registry.go [hunk 1]
```diff
@@ -41,18 +41,28 @@ LABEL %s=%s
 LABEL maintainers="%v"
 COPY / /
 `, internal.ImageLabel, meta.Name, meta.Maintainers)
-	df := filepath.Join(app.Path, "__Dockerfile-docker-app__")
+	dir, err := ioutil.TempDir("", app.Name)
+	if err != nil {
+		return "", errors.Wrap(err, "cannot create temporary directoryr")
```
Comment (chris-crone) [inline internal/packager/registry.go]: directoryr -> directory

File: types/types.go [hunk 2]
```diff
@@ -39,6 +39,19 @@ func (a *App) Metadata() []byte {
 	return a.metadataContent
 }
 
+func (a *App) Extract(path string) error {
```
Comment (mnottale) [inline types/types.go]: Lint error, missing method doc.

File: types/types.go [hunk 3]
```diff
@@ -39,6 +39,19 @@ func (a *App) Metadata() []byte {
...
+	if err := ioutil.WriteFile(filepath.Join(path, internal.MetadataFileName), a.Metadata(), 0755); err != nil {
```
Comment (mnottale) [inline types/types.go]: nit: mode should rather be 0644, no need for exec bit
